### PR TITLE
Remove broken alternatives

### PR DESCRIPTION
**Pull request by porunov**
This PR is related to: #49
It removes broken alternatives and use symbolic links instead of them.

### CODE REVIEW

**Comment by porunov** [comment]
@sroegner  clould you please merge this PR? 
Regards

**Comment by porunov** [comment]
Hello @vutny 

I had a pillar file with `java_home: /usr/java/default` but then I changed it to `java_home: /usr/lib/java`.

Then I refreshed it `salt '*' saltutil.refresh_pillar`.

I don't have `java_home` grain on the minion.

Also, by modifying `sun-java/env.sls` I checked all variables in settings. The minion server didn't have any variables with the value: `/usr/java/default`.

I still don't know what is the problem with alternatives and where it got `/usr/java/default`. Right now I am using a modified version of `sun-java-formula` (with this PR) and everything works correctly.

**Comment by porunov** [comment]
@noelmcloughlin 
Seems it is the solution which will satisfy everybody. Yep, I will add changes in several hours.

**Comment by porunov** [comment]
@noelmcloughlin @vutny 
I've made changes. Now alternatives is supported only when `alt_priority` is set. In other case simple links will do the job.

**Comment by noelmcloughlin** [comment]
Thanks @porunov verified on OpenSUSE.

**Comment by porunov** [comment]
Thanks @noelmcloughlin for reviewing
verified on CentOS 7.4

**Pull request merged**
