### PR TITLE
Update Java default version and install cURL

### PR DESCRIPTION
**Pull request by psmiraglia**
Set the default Java version to the latest one (`1.8.0_121`) and includes the `curl` package installation as dependency (because used to download Java files).

### CODE REVIEW

**Comment by myoung34** [comment]
Is there a better way to do this? Looks like its bumped again to `131`

@blbradley any thoughts? Im not a fan of version chasing

**Comment by johnkeates** [comment]
I've created a formula that does exactly this, but it's for Debian and the likes which can use webupd8 that has automatic upgrade support but also allows version pinning between the last two major Java releases. I'm not sure if such a service exists for the RPM side of town, but that might make this a whole lot easier.

**Comment by blbradley** [comment]
I'd leave the installation of curl to users. Multiple formulas installing curl get weird quick.

Users should be updating their own sun-javas through pillar on their own update schedule.

@myoung34 I'm not a fan either.

@johnkeates Sounds fancy! Feel free to share in some way.

**Comment by johnkeates** [comment]
@blbradley It's used on some internal project, but I Gist'ed the notes (a partial SLS with some quick-n-dirty sed replacements for our internal names): https://gist.github.com/johnkeates/b855d6309e051184c33d5cef8784f9c1

I'll be put into an update for the logstash-formula as well (and possibly others), in a more refined form.

Basically, in that Gist, you get a repo, some presets so the installer doesn't ask for questions, and then it installs Java and makes it the default runtime (instead of OpenJDK).

**Comment by sroegner** [comment]
@myoung34 the original intent of the formula wasn't to provide the latest and greatest at any given point but to deliver a (pillar-) configured stable version to as many OS platforms as possible (hence the use of the tarball) to support formulas that depend on java like zookeeper, hadoop and such.
Speaking of this: it appears to me that the otn download stopped working in the form it is implemented here (returning a HTTP 404) - has anyone else seen this?

**Comment by myoung34** [comment]
@sroegner ironically me discussing this came from your PR in https://github.com/saltstack-formulas/jenkins-formula/pull/69

**Comment by psmiraglia** [comment]
Hi, the PR was just to update the default values in order to have a ready-to-use formula. As @myoung34 said, due to 131 bump, the PR now does not make sense. Feel free to close.

**Pull request closed without merging**
